from tkinter import *
from PIL import Image, ImageTk

root=Tk()

button_size=(100, 100)

# create image object
img1=Image.open("test_images/test_image1.png")
img2=Image.open("test_images/test_image2.png")
img3=Image.open("test_images/test_image3.png")
img4=Image.open("test_images/test_image4.png")
img5=Image.open("test_images/test_image5.png")
img6=Image.open("test_images/test_image6.png")
img7=Image.open("test_images/test_image7.png")
img8=Image.open("test_images/test_image8.png")
img9=Image.open("test_images/test_image9.png")
img10=Image.open("test_images/test_image10.png")
img11=Image.open("test_images/test_image11.png")
img12=Image.open("test_images/test_image12.png")
img13=Image.open("test_images/test_image13.png")
img14=Image.open("test_images/test_image14.png")
img15=Image.open("test_images/test_image15.png")
img16=Image.open("test_images/test_image16.png")

# resize them to fit button size preserving aspect ratio
img1.thumbnail(button_size)
img2.thumbnail(button_size)
img3.thumbnail(button_size)
img4.thumbnail(button_size)
img5.thumbnail(button_size)
img6.thumbnail(button_size)
img7.thumbnail(button_size)
img8.thumbnail(button_size)
img9.thumbnail(button_size)
img10.thumbnail(button_size)
img11.thumbnail(button_size)
img12.thumbnail(button_size)
img13.thumbnail(button_size)
img14.thumbnail(button_size)
img15.thumbnail(button_size)
img16.thumbnail(button_size)

# make images Tkinter-compatible
img1=ImageTk.PhotoImage(img1)
img2=ImageTk.PhotoImage(img2)
img3=ImageTk.PhotoImage(img3)
img4=ImageTk.PhotoImage(img4)
img5=ImageTk.PhotoImage(img5)
img6=ImageTk.PhotoImage(img6)
img7=ImageTk.PhotoImage(img7)
img8=ImageTk.PhotoImage(img8)
img9=ImageTk.PhotoImage(img9)
img10=ImageTk.PhotoImage(img10)
img11=ImageTk.PhotoImage(img11)
img12=ImageTk.PhotoImage(img12)
img13=ImageTk.PhotoImage(img13)
img14=ImageTk.PhotoImage(img14)
img15=ImageTk.PhotoImage(img15)
img16=ImageTk.PhotoImage(img16)

# create buttons with images in them
button1=Button(image=img1, height=100, width=100)
button2=Button(image=img2, height=100, width=100)
button3=Button(image=img3, height=100, width=100)
button4=Button(image=img4, height=100, width=100)
button5=Button(image=img5, height=100, width=100)
button6=Button(image=img6, height=100, width=100)
button7=Button(image=img7, height=100, width=100)
button8=Button(image=img8, height=100, width=100)
button9=Button(image=img9, height=100, width=100)
button10=Button(image=img10, height=100, width=100)
button11=Button(image=img11, height=100, width=100)
button12=Button(image=img12, height=100, width=100)
button13=Button(image=img13, height=100, width=100)
button14=Button(image=img14, height=100, width=100)
button15=Button(image=img15, height=100, width=100)
button16=Button(image=img16, height=100, width=100)

# put buttons on grid
button1.grid(row=0,column=0)
button2.grid(row=0,column=1)
button3.grid(row=0,column=2)
button4.grid(row=0,column=3)
button5.grid(row=1,column=0)
button6.grid(row=1,column=1)
button7.grid(row=1,column=2)
button8.grid(row=1,column=3)
button9.grid(row=2,column=0)
button10.grid(row=2,column=1)
button11.grid(row=2,column=2)
button12.grid(row=2,column=3)
button13.grid(row=3,column=0)
button14.grid(row=3,column=1)
button15.grid(row=3,column=2)
button16.grid(row=3,column=3)


root.mainloop()